"""Static Replay exporters."""

from __future__ import annotations

import html
import json
import os
import shutil
from pathlib import Path
from textwrap import shorten

from backend.api.serialize import to_dict
from backend.collectors.utils import default_nastech_dir
from backend.models.replay import ReplayDetail, ReplayExportResult
from backend.services.replay_normalizer import _hash_payload
from backend.services.replay_redactor import scan_replay
from backend.services.replay_signer import sign_receipt_hashes


REDACTION_NOTICE = "Generated by NasTech Replay. Sensitive fields redacted in Safe Share Mode."
DEFAULT_SETTINGS = {
    "schema_version": "0.1",
    "local_only": True,
    "export_dir": None,
    "safe_share_mode": True,
    "include_raw_logs": False,
    "include_screenshots": False,
}


def default_replay_dir() -> Path:
    nastech_home = Path(default_nastech_dir())
    root = os.environ.get("NASTECH_HUD_REPLAY_DIR")
    if root:
        return Path(root).expanduser()
    return nastech_home.parent / ".nastech-hud" / "replays"


def get_replay_settings() -> dict:
    root = default_replay_dir()
    path = root / "settings.json"
    if not path.exists():
        return {**DEFAULT_SETTINGS, "export_dir": str(root)}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {**DEFAULT_SETTINGS, "export_dir": str(root)}
    settings = {**DEFAULT_SETTINGS, **{key: data.get(key) for key in DEFAULT_SETTINGS if key in data}}
    settings["export_dir"] = str(root)
    settings["local_only"] = True
    settings["safe_share_mode"] = True
    return settings


def update_replay_settings(settings: dict) -> dict:
    root = default_replay_dir()
    root.mkdir(parents=True, exist_ok=True)
    current = get_replay_settings()
    allowed = {
        "safe_share_mode": True,
        "include_raw_logs": bool(settings.get("include_raw_logs", current["include_raw_logs"])),
        "include_screenshots": bool(settings.get("include_screenshots", current["include_screenshots"])),
    }
    next_settings = {
        **DEFAULT_SETTINGS,
        **allowed,
        "local_only": True,
        "export_dir": str(root),
    }
    _write_text(root / "settings.json", json.dumps(next_settings, indent=2, sort_keys=True))
    return next_settings


def redacted_detail(detail: ReplayDetail) -> ReplayDetail:
    redacted = scan_replay(detail)
    for finding in redacted.redactions:
        finding.preview = finding.replacement
    if redacted.receipt:
        receipt_payload = to_dict(redacted.receipt)
        receipt_payload["hashes"]["receipt_hash"] = None
        redacted.receipt.hashes.receipt_hash = _hash_payload(receipt_payload)
        redacted.run.hashes.receipt_hash = redacted.receipt.hashes.receipt_hash
    return redacted


def _run_dir(detail: ReplayDetail) -> Path:
    path = default_replay_dir() / "runs" / detail.run.replay_id
    path.mkdir(parents=True, exist_ok=True)
    return path


def _write_text(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def _update_publish_manifests(replay_id: str, updater) -> None:
    root = default_replay_dir()
    for visibility in ("public", "unlisted"):
        manifest_path = root / visibility / replay_id / "publish.json"
        if not manifest_path.exists():
            continue
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        if not isinstance(manifest, dict):
            continue
        updater(manifest)
        _write_text(manifest_path, json.dumps(manifest, indent=2, sort_keys=True))


def _write_receipt(detail: ReplayDetail, run_dir: Path) -> None:
    if detail.receipt is None:
        return
    receipt = to_dict(detail.receipt)
    receipt.update(sign_receipt_hashes(
        detail.run.hashes.receipt_hash or "",
        detail.run.hashes.redacted_replay_hash or "",
        default_replay_dir(),
    ))
    _write_text(run_dir / "receipt.json", json.dumps(receipt, indent=2, sort_keys=True))


def _update_index(detail: ReplayDetail, exported_path: Path) -> None:
    root = default_replay_dir()
    root.mkdir(parents=True, exist_ok=True)
    index_path = root / "index.json"
    try:
        index = json.loads(index_path.read_text(encoding="utf-8")) if index_path.exists() else {"schema_version": "0.1", "runs": []}
    except (json.JSONDecodeError, OSError):
        index = {"schema_version": "0.1", "runs": []}
    runs = [item for item in index.get("runs", []) if item.get("replay_id") != detail.run.replay_id]
    runs.insert(0, {
        "replay_id": detail.run.replay_id,
        "source_session_id": detail.run.source_session_id,
        "title": detail.run.title,
        "status": detail.run.status,
        "started_at": detail.run.started_at,
        "updated_at": detail.run.updated_at,
        "redaction_status": detail.run.redaction_status,
        "receipt_hash": detail.run.hashes.receipt_hash,
        "redacted_replay_hash": detail.run.hashes.redacted_replay_hash,
        "last_export_path": str(exported_path),
    })
    index["runs"] = runs[:250]
    _write_text(index_path, json.dumps(index, indent=2, sort_keys=True))


def _update_skill_index(detail: ReplayDetail) -> None:
    root = default_replay_dir()
    root.mkdir(parents=True, exist_ok=True)
    path = root / "skills.json"
    try:
        index = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {"schema_version": "0.1", "skills": []}
    except (json.JSONDecodeError, OSError):
        index = {"schema_version": "0.1", "skills": []}
    skills = {item.get("name"): item for item in index.get("skills", []) if item.get("name")}
    receipt_skills = detail.receipt.skills_used if detail.receipt else []
    mutation_events = [
        event for event in detail.events
        if event.type in {"skill_created", "skill_modified"} and event.metadata.get("skill_name")
    ]
    for skill in receipt_skills:
        name = skill.get("name")
        if not name:
            continue
        entry = skills.setdefault(name, {
            "name": name,
            "version": skill.get("version"),
            "hash": skill.get("hash"),
            "runs_used_in": [],
            "usage_count": 0,
            "success_count": 0,
            "success_rate": None,
            "first_used_at": detail.run.started_at or detail.run.created_at,
            "last_used_at": detail.run.started_at or detail.run.updated_at,
            "mutation_receipts": [],
        })
        already_indexed = detail.run.replay_id in entry["runs_used_in"]
        if detail.run.replay_id not in entry["runs_used_in"]:
            entry["runs_used_in"].insert(0, detail.run.replay_id)
        if entry.get("first_used_at") is None:
            entry["first_used_at"] = detail.run.started_at or detail.run.created_at
        entry["last_used_at"] = detail.run.started_at or detail.run.updated_at or entry.get("last_used_at")
        entry["usage_count"] = len(entry["runs_used_in"])
        entry["success_count"] = int(entry.get("success_count") or 0)
        if detail.run.status == "success" and not already_indexed:
            entry["success_count"] += 1
        entry["success_rate"] = round(entry["success_count"] / entry["usage_count"], 4) if entry["usage_count"] else None
        if entry.get("hash") is None and skill.get("hash"):
            entry["hash"] = skill.get("hash")
        if entry.get("version") is None and skill.get("version"):
            entry["version"] = skill.get("version")
        for event in mutation_events:
            if event.metadata.get("skill_name") != name:
                continue
            mutation_receipt = {
                "event_id": event.event_id,
                "event_type": event.type,
                "replay_id": detail.run.replay_id,
                "source_session_id": detail.run.source_session_id,
                "timestamp": event.timestamp,
                "receipt_hash": detail.run.hashes.receipt_hash,
                "redacted_replay_hash": detail.run.hashes.redacted_replay_hash,
            }
            receipts = entry.setdefault("mutation_receipts", [])
            if not any(item.get("event_id") == event.event_id for item in receipts):
                receipts.insert(0, mutation_receipt)
    public_skills = []
    for entry in skills.values():
        clean = dict(entry)
        clean.pop("_successful_runs", None)
        public_skills.append(clean)
    index["skills"] = sorted(public_skills, key=lambda item: item["usage_count"], reverse=True)
    _write_text(path, json.dumps(index, indent=2, sort_keys=True))


def get_skill_provenance_index() -> dict:
    path = default_replay_dir() / "skills.json"
    if not path.exists():
        return {"schema_version": "0.1", "skills": []}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {"schema_version": "0.1", "skills": []}
    return data if isinstance(data, dict) else {"schema_version": "0.1", "skills": []}


def get_replay_gallery() -> dict:
    root = default_replay_dir()
    entries = []
    for visibility in ("public", "unlisted"):
        directory = root / visibility
        if not directory.exists():
            continue
        for manifest_path in sorted(directory.glob("*/publish.json")):
            try:
                manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, OSError):
                continue
            if isinstance(manifest, dict):
                entries.append({
                    "visibility": visibility,
                    "manifest_path": str(manifest_path),
                    "replay_id": manifest.get("replay_id"),
                    "title": manifest.get("title"),
                    "entry": manifest.get("entry"),
                    "receipt_hash": manifest.get("receipt_hash"),
                    "redacted_replay_hash": manifest.get("redacted_replay_hash"),
                    "view_count": int(manifest.get("view_count") or 0),
                    "fork_count": int(manifest.get("fork_count") or 0),
                })
    return {"schema_version": "0.1", "entries": entries}


def _write_gallery_index() -> Path:
    root = default_replay_dir()
    gallery = get_replay_gallery()
    cards = []
    for entry in gallery["entries"]:
        title = html.escape(str(entry.get("title") or entry.get("replay_id") or "Untitled replay"))
        visibility = html.escape(str(entry.get("visibility") or "unlisted"))
        entry_path = html.escape(str(entry.get("entry") or ""))
        receipt_hash = html.escape(str(entry.get("receipt_hash") or "pending"))
        cards.append(
            f"<article><h2>{title}</h2><p>{visibility}</p>"
            f"<a href=\"{entry_path}\">Open replay</a>"
            f"<small>views {entry.get('view_count', 0)} · forks {entry.get('fork_count', 0)}</small>"
            f"<code>{receipt_hash}</code></article>"
        )
    content = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>NasTech Replay Gallery</title>
  <style>
    body {{ margin:0; font-family:system-ui,sans-serif; background:#071211; color:#d7fffb; }}
    main {{ max-width:1080px; margin:0 auto; padding:32px; }}
    h1 {{ color:#5ef6d2; }}
    .grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(260px,1fr)); gap:16px; }}
    article {{ border:1px solid #1f4f4a; background:#0c2220; padding:16px; }}
    h2 {{ margin:0 0 8px; color:#d7fffb; font-size:18px; }}
    p, small, code {{ color:#95aaa7; display:block; margin:8px 0; word-break:break-all; }}
    a {{ color:#5ef6d2; }}
  </style>
</head>
<body>
  <main>
    <h1>NasTech Replay Gallery</h1>
    <p>Local static index generated by NasTech Replay. No cloud upload was performed.</p>
    <section class="grid">{''.join(cards) or '<article><h2>No published replays</h2><p>Publish a replay locally to list it here.</p></article>'}</section>
  </main>
</body>
</html>
"""
    path = root / "gallery.html"
    root.mkdir(parents=True, exist_ok=True)
    _write_text(path, content)
    return path


def _finalize_export(path: Path, detail: ReplayDetail) -> ReplayExportResult:
    run_dir = _run_dir(detail)
    _write_receipt(detail, run_dir)
    _update_index(detail, path)
    _update_skill_index(detail)
    return _export_result(path, detail)


def _write(path: Path, content: str, mode: str = "w") -> ReplayExportResult:
    _write_text(path, content)
    return ReplayExportResult(
        ok=True,
        export_path=str(path),
        receipt_hash=None,
        redacted_replay_hash=None,
        redaction_notice=REDACTION_NOTICE,
    )


def _export_result(path: Path, detail: ReplayDetail) -> ReplayExportResult:
    return ReplayExportResult(
        ok=True,
        export_path=str(path),
        receipt_hash=detail.run.hashes.receipt_hash,
        redacted_replay_hash=detail.run.hashes.redacted_replay_hash,
        redaction_notice=REDACTION_NOTICE,
    )


def export_json(detail: ReplayDetail) -> ReplayExportResult:
    redacted = redacted_detail(detail)
    path = _run_dir(redacted) / "replay.redacted.json"
    payload = {
        "schema_version": "0.1",
        "redaction_notice": REDACTION_NOTICE,
        "replay": to_dict(redacted),
    }
    _write_text(path, json.dumps(payload, indent=2, sort_keys=True))
    return _finalize_export(path, redacted)


def _timeline_markdown(detail: ReplayDetail) -> str:
    rows = []
    for event in detail.events:
        rows.append(f"- **{event.title}** ({event.type}): {event.summary}")
    return "\n".join(rows) or "- No timeline events detected."


def _artifacts_markdown(detail: ReplayDetail) -> str:
    rows = []
    for artifact in detail.artifacts:
        rows.append(f"- **{artifact.title}** ({artifact.type}): {artifact.summary or 'No summary.'}")
    return "\n".join(rows) or "- No proof artifacts detected."


def export_markdown(detail: ReplayDetail) -> ReplayExportResult:
    redacted = redacted_detail(detail)
    path = _run_dir(redacted) / "replay.md"
    receipt_json = json.dumps(to_dict(redacted.receipt), indent=2, sort_keys=True)
    content = f"""# NasTech Replay: {redacted.run.title}

**Status:** {redacted.run.status}  
**Duration:** {redacted.run.duration_ms or "Unknown"} ms  
**Cost:** {redacted.run.total_cost_usd if redacted.run.total_cost_usd is not None else "Unknown"}  
**Model:** {redacted.run.primary_model or "Unknown"}  
**Tools:** {redacted.run.counts.tool_calls}  
**Skills:** {redacted.run.counts.skills_used}  

## Timeline

{_timeline_markdown(redacted)}

## Proof Artifacts

{_artifacts_markdown(redacted)}

## Receipt

```json
{receipt_json}
```

{REDACTION_NOTICE}
"""
    _write_text(path, content)
    return _finalize_export(path, redacted)


def export_html(detail: ReplayDetail) -> ReplayExportResult:
    redacted = redacted_detail(detail)
    path = _run_dir(redacted) / "replay.html"
    timeline = "\n".join(
        f"<li><strong>{html.escape(event.title)}</strong> "
        f"<span>{html.escape(event.type)}</span><p>{html.escape(event.summary)}</p></li>"
        for event in redacted.events
    ) or "<li>No timeline events detected.</li>"
    artifacts = "\n".join(
        f"<li><strong>{html.escape(artifact.title)}</strong> "
        f"<span>{html.escape(artifact.type)}</span><p>{html.escape(artifact.summary or 'No summary.')}</p></li>"
        for artifact in redacted.artifacts
    ) or "<li>No proof artifacts detected.</li>"
    payload = html.escape(json.dumps(to_dict(redacted), indent=2, sort_keys=True))
    content = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>NasTech Replay: {html.escape(redacted.run.title)}</title>
  <style>
    body {{ font-family: system-ui, sans-serif; margin: 0; background: #071211; color: #d7fffb; }}
    main {{ max-width: 980px; margin: 0 auto; padding: 32px; }}
    section {{ border: 1px solid #1f4f4a; margin: 16px 0; padding: 16px; }}
    h1, h2 {{ color: #5ef6d2; }}
    li {{ margin: 12px 0; }}
    span {{ color: #95aaa7; font-size: 12px; text-transform: uppercase; }}
    pre {{ overflow: auto; background: #020706; padding: 16px; }}
  </style>
</head>
<body>
  <main>
    <h1>NasTech Replay: {html.escape(redacted.run.title)}</h1>
    <section>
      <h2>Run Receipt</h2>
      <p>Status: {html.escape(redacted.run.status)}</p>
      <p>Model: {html.escape(redacted.run.primary_model or "Unknown")}</p>
      <p>Tools: {redacted.run.counts.tool_calls}</p>
      <p>Receipt hash: {html.escape(redacted.run.hashes.receipt_hash or "Pending")}</p>
    </section>
    <section>
      <h2>Timeline</h2>
      <ul>{timeline}</ul>
    </section>
    <section>
      <h2>Proof Artifacts</h2>
      <ul>{artifacts}</ul>
    </section>
    <section>
      <h2>Redaction Notice</h2>
      <p>{html.escape(REDACTION_NOTICE)}</p>
    </section>
    <section>
      <h2>Raw Redacted JSON</h2>
      <pre>{payload}</pre>
    </section>
  </main>
</body>
</html>
"""
    _write_text(path, content)
    return _finalize_export(path, redacted)


def export_fork_json(detail: ReplayDetail) -> ReplayExportResult:
    redacted = redacted_detail(detail)
    path = _run_dir(redacted) / "fork.json"
    prompt = next((event.summary for event in redacted.events if event.type == "prompt"), redacted.run.title)
    payload = {
        "schema_version": "0.1",
        "source": "nastech-replay",
        "run_title": redacted.run.title,
        "original_prompt_redacted": prompt,
        "recommended_model": redacted.run.primary_model,
        "skills": redacted.receipt.skills_used if redacted.receipt else [],
        "toolsets": sorted({str(event.metadata.get("tool_name")) for event in redacted.events if event.metadata.get("tool_name")}),
        "project_context_summary": "Private project context removed.",
        "steps": [event.summary for event in redacted.events if event.type in {"prompt", "assistant_message", "tool_call", "terminal_command"}][:20],
        "redaction_notice": "Private data removed.",
    }
    _write_text(path, json.dumps(payload, indent=2, sort_keys=True))
    _update_publish_manifests(redacted.run.replay_id, lambda manifest: manifest.update({
        "fork_count": int(manifest.get("fork_count") or 0) + 1,
    }))
    _write_gallery_index()
    return _finalize_export(path, redacted)


SHARE_CARD_FORMATS = {
    "wide": (1200, 630, "share-card.png"),
    "landscape": (1600, 900, "share-card-1600x900.png"),
    "square": (1080, 1080, "share-card-square.png"),
    "story": (1080, 1920, "share-card-story.png"),
}


def export_share_card_png(detail: ReplayDetail, card_format: str = "wide") -> ReplayExportResult:
    """Generate a social share card PNG from the redacted receipt."""
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError as exc:
        raise RuntimeError("Pillow is required to generate PNG share cards") from exc

    redacted = redacted_detail(detail)
    width, height, filename = SHARE_CARD_FORMATS.get(card_format, SHARE_CARD_FORMATS["wide"])
    path = _run_dir(redacted) / filename

    bg = (7, 18, 17)
    panel = (12, 34, 32)
    primary = (94, 246, 210)
    text = (215, 255, 251)
    dim = (143, 170, 166)
    border = (31, 79, 74)
    success = (86, 220, 146)

    image = Image.new("RGB", (width, height), bg)
    draw = ImageDraw.Draw(image)

    def font(size: int, bold: bool = False):
        candidates = [
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
            "/usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf",
        ]
        for candidate in candidates:
            if Path(candidate).exists():
                return ImageFont.truetype(candidate, size)
        return ImageFont.load_default()

    scale = min(width / 1200, height / 630)
    margin = max(42, int(48 * scale))
    title_font = font(max(38, int(56 * scale)), True)
    label_font = font(max(18, int(22 * scale)))
    metric_font = font(max(26, int(34 * scale)), True)
    mono_font = font(max(16, int(20 * scale)))

    draw.rectangle((margin, margin, width - margin, height - margin), fill=panel, outline=border, width=2)
    draw.text((margin + 34, margin + 30), "NASTECH REPLAY", fill=primary, font=label_font)

    title = shorten(redacted.run.title, width=42 if height > width else 54, placeholder="...")
    title_y = margin + 78
    draw.text((margin + 34, title_y), title, fill=text, font=title_font)

    status_color = success if redacted.run.status == "success" else primary
    status_y = title_y + int(92 * scale)
    draw.rounded_rectangle((margin + 34, status_y, margin + 210, status_y + 48), radius=6, outline=status_color, width=2)
    draw.text((margin + 60, status_y + 10), redacted.run.status.upper(), fill=status_color, font=label_font)

    tests_total = (redacted.run.counts.tests_passed or 0) + (redacted.run.counts.tests_failed or 0)
    metrics = [
        ("Duration", f"{round((redacted.run.duration_ms or 0) / 1000)}s" if redacted.run.duration_ms else "Unknown"),
        ("Cost", f"${redacted.run.total_cost_usd:.4f}" if redacted.run.total_cost_usd is not None else "Unknown"),
        ("Tool calls", str(redacted.run.counts.tool_calls)),
        ("Skills", str(redacted.run.counts.skills_used)),
        ("Files", str(redacted.run.counts.files_changed) if redacted.run.counts.files_changed is not None else "Unknown"),
        ("Tests", f"{redacted.run.counts.tests_passed}/{tests_total} passed" if tests_total else "Not detected"),
    ]
    columns = 2 if height >= width else 3
    metric_area_width = width - (margin * 2) - 68
    column_width = max(220, metric_area_width // columns)
    x_positions = [margin + 34 + (column_width * index) for index in range(columns)]
    metric_start_y = status_y + int(94 * scale)
    row_gap = max(112, int(112 * scale))
    for index, (label, value) in enumerate(metrics):
        x = x_positions[index % columns]
        y = metric_start_y + row_gap * (index // columns)
        draw.text((x, y), label.upper(), fill=dim, font=label_font)
        draw.text((x, y + 34), value, fill=primary, font=metric_font)

    replay_hash = redacted.run.hashes.redacted_replay_hash or "hash pending"
    footer_y = height - margin - 66
    draw.line((margin + 34, footer_y - 20, width - margin - 34, footer_y - 20), fill=border, width=1)
    draw.text((margin + 34, footer_y), f"Replay hash: {replay_hash}", fill=dim, font=mono_font)
    draw.text((width - margin - 190, footer_y), "View replay", fill=primary, font=mono_font)

    image.save(path, format="PNG", optimize=True)
    return _finalize_export(path, redacted)


def publish_replay(detail: ReplayDetail, visibility: str = "unlisted") -> ReplayExportResult:
    """Publish a replay to a local static public/unlisted directory."""
    if visibility not in {"public", "unlisted"}:
        visibility = "unlisted"
    redacted = redacted_detail(detail)
    run_dir = _run_dir(redacted)
    if not (run_dir / "replay.html").exists():
        export_html(detail)
    if not (run_dir / "replay.redacted.json").exists():
        export_json(detail)
    if not (run_dir / "receipt.json").exists():
        _write_receipt(redacted, run_dir)

    target = default_replay_dir() / visibility / redacted.run.replay_id
    target.mkdir(parents=True, exist_ok=True)
    for name in ["replay.html", "replay.redacted.json", "receipt.json", "share-card.png", "replay.md", "fork.json"]:
        src = run_dir / name
        if src.exists():
            dst = target / name
            if src.suffix == ".png":
                dst.write_bytes(src.read_bytes())
            else:
                _write_text(dst, src.read_text(encoding="utf-8"))
    manifest = {
        "schema_version": "0.1",
        "source": "nastech-replay",
        "visibility": visibility,
        "replay_id": redacted.run.replay_id,
        "title": redacted.run.title,
        "entry": str(target / "replay.html"),
        "receipt_hash": redacted.run.hashes.receipt_hash,
        "redacted_replay_hash": redacted.run.hashes.redacted_replay_hash,
        "view_count": 0,
        "fork_count": 0,
    }
    manifest_path = target / "publish.json"
    _write_text(manifest_path, json.dumps(manifest, indent=2, sort_keys=True))
    _write_gallery_index()
    return _export_result(manifest_path, redacted)


def unpublish_replay(detail: ReplayDetail, visibility: str = "unlisted") -> ReplayExportResult:
    """Remove a locally published replay from public/unlisted directories."""
    if visibility not in {"public", "unlisted"}:
        visibility = "unlisted"
    target = default_replay_dir() / visibility / detail.run.replay_id
    if target.exists():
        shutil.rmtree(target)
    _write_gallery_index()
    return ReplayExportResult(
        ok=True,
        export_path=str(target),
        receipt_hash=detail.run.hashes.receipt_hash,
        redacted_replay_hash=detail.run.hashes.redacted_replay_hash,
        redaction_notice="Local publish directory removed.",
    )


def record_gallery_view(detail: ReplayDetail, visibility: str = "unlisted") -> ReplayExportResult:
    """Increment the local view counter for a published replay manifest."""
    if visibility not in {"public", "unlisted"}:
        visibility = "unlisted"
    manifest_path = default_replay_dir() / visibility / detail.run.replay_id / "publish.json"
    if not manifest_path.exists():
        return ReplayExportResult(
            ok=False,
            export_path=str(manifest_path),
            receipt_hash=detail.run.hashes.receipt_hash,
            redacted_replay_hash=detail.run.hashes.redacted_replay_hash,
            redaction_notice="Replay is not locally published.",
        )

    def increment(manifest: dict) -> None:
        manifest["view_count"] = int(manifest.get("view_count") or 0) + 1

    _update_publish_manifests(detail.run.replay_id, increment)
    _write_gallery_index()
    return ReplayExportResult(
        ok=True,
        export_path=str(manifest_path),
        receipt_hash=detail.run.hashes.receipt_hash,
        redacted_replay_hash=detail.run.hashes.redacted_replay_hash,
        redaction_notice="Local gallery view recorded.",
    )


def export_clip_html(detail: ReplayDetail) -> ReplayExportResult:
    """Generate a standalone animated NasTech Clip HTML artifact."""
    redacted = redacted_detail(detail)
    path = _run_dir(redacted) / "clip.html"
    timeline_items = "\n".join(
        f"<li style=\"animation-delay:{index * 0.45:.2f}s\"><b>{html.escape(event.title)}</b><span>{html.escape(event.summary)}</span></li>"
        for index, event in enumerate(redacted.events[:8])
    ) or "<li><b>No timeline</b><span>No events detected.</span></li>"
    content = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>NasTech Clip: {html.escape(redacted.run.title)}</title>
  <style>
    body {{ margin:0; min-height:100vh; display:grid; place-items:center; background:#071211; color:#d7fffb; font-family:system-ui,sans-serif; }}
    main {{ width:min(960px, calc(100vw - 48px)); border:1px solid #1f4f4a; padding:36px; background:#0c2220; }}
    h1 {{ margin:0 0 8px; color:#5ef6d2; font-size:42px; }}
    .metrics {{ display:flex; gap:24px; margin:20px 0; color:#95aaa7; }}
    .metrics b {{ color:#5ef6d2; display:block; font-size:28px; }}
    li {{ opacity:0; transform:translateY(12px); animation:rise .45s ease forwards; margin:14px 0; list-style:none; border-left:2px solid #5ef6d2; padding-left:14px; }}
    li span {{ display:block; color:#95aaa7; margin-top:4px; }}
    footer {{ margin-top:24px; color:#95aaa7; font-size:13px; }}
    @keyframes rise {{ to {{ opacity:1; transform:translateY(0); }} }}
  </style>
</head>
<body>
  <main>
    <h1>{html.escape(redacted.run.title)}</h1>
    <div>NasTech Replay Clip</div>
    <div class="metrics">
      <div><b>{html.escape(redacted.run.status)}</b>Status</div>
      <div><b>{redacted.run.counts.tool_calls}</b>Tool calls</div>
      <div><b>{redacted.run.counts.files_changed if redacted.run.counts.files_changed is not None else "?"}</b>Files</div>
      <div><b>{redacted.run.counts.tests_passed if redacted.run.counts.tests_passed is not None else "?"}</b>Tests passed</div>
    </div>
    <ol>{timeline_items}</ol>
    <footer>Receipt hash: {html.escape(redacted.run.hashes.receipt_hash or "pending")} · {html.escape(REDACTION_NOTICE)}</footer>
  </main>
</body>
</html>
"""
    _write_text(path, content)
    return _finalize_export(path, redacted)
