from datetime import datetime
import json

from backend.collectors.models import SessionInfo
from backend.services.replay_exporter import (
    export_fork_json,
    export_html,
    export_json,
    export_clip_html,
    export_markdown,
    export_share_card_png,
    get_skill_provenance_index,
    get_replay_settings,
    get_replay_gallery,
    publish_replay,
    record_gallery_view,
    unpublish_replay,
    update_replay_settings,
)
from backend.services.replay_normalizer import normalize_session


def _detail():
    session = SessionInfo(
        id="session-export",
        source="cli",
        title="Export run",
        started_at=datetime.fromtimestamp(100),
        ended_at=datetime.fromtimestamp(120),
        message_count=1,
        tool_call_count=0,
        input_tokens=1,
        output_tokens=1,
        model="gpt-test",
    )
    return normalize_session(
        session,
        [{"id": 1, "role": "user", "content": "Use /home/joey/app and email person@example.com", "timestamp": 101}],
    )


def _skill_detail():
    session = SessionInfo(
        id="session-skill",
        source="cli",
        title="Skill run",
        started_at=datetime.fromtimestamp(100),
        ended_at=datetime.fromtimestamp(120),
        message_count=1,
        tool_call_count=0,
        input_tokens=1,
        output_tokens=1,
    )
    return normalize_session(
        session,
        [{"id": 1, "role": "assistant", "content": "Using skill auth-helper for login.", "timestamp": 101}],
    )


def _skill_mutation_detail():
    session = SessionInfo(
        id="session-skill-mutation",
        source="cli",
        title="Skill mutation run",
        started_at=datetime.fromtimestamp(100),
        ended_at=datetime.fromtimestamp(120),
        message_count=1,
        tool_call_count=0,
        input_tokens=1,
        output_tokens=1,
    )
    return normalize_session(
        session,
        [{"id": 1, "role": "assistant", "content": "Created skill auth-helper for login.", "timestamp": 101}],
    )


def test_export_json_markdown_html_and_fork_use_redacted_payloads(tmp_path, monkeypatch) -> None:
    monkeypatch.setenv("NASTECH_HUD_REPLAY_DIR", str(tmp_path))
    detail = _detail()

    results = [
        export_json(detail),
        export_markdown(detail),
        export_html(detail),
        export_clip_html(detail),
        export_share_card_png(detail),
        export_fork_json(detail),
    ]

    for result in results:
        assert result.ok is True
        path = tmp_path / "runs" / detail.run.replay_id / result.export_path.split("/")[-1]
        if path.suffix == ".png":
            image_bytes = path.read_bytes()
            assert image_bytes.startswith(b"\x89PNG\r\n\x1a\n")
            assert b"person@example.com" not in image_bytes
            assert b"/home/joey" not in image_bytes
            continue
        text = path.read_text(encoding="utf-8")
        assert "Generated by NasTech Replay" in text or "Private data removed" in text
        assert "person@example.com" not in text
        assert "/home/joey" not in text

    fork = json.loads((tmp_path / "runs" / detail.run.replay_id / "fork.json").read_text(encoding="utf-8"))
    assert fork["schema_version"] == "0.1"
    assert fork["source"] == "nastech-replay"

    receipt = json.loads((tmp_path / "runs" / detail.run.replay_id / "receipt.json").read_text(encoding="utf-8"))
    index = json.loads((tmp_path / "index.json").read_text(encoding="utf-8"))

    assert receipt["replay_id"] == detail.run.replay_id
    assert index["schema_version"] == "0.1"
    assert index["runs"][0]["replay_id"] == detail.run.replay_id
    index_text = json.dumps(index)
    assert "person@example.com" not in index_text
    assert "/home/joey" not in index_text


def test_share_card_exports_optional_formats(tmp_path, monkeypatch) -> None:
    from PIL import Image

    monkeypatch.setenv("NASTECH_HUD_REPLAY_DIR", str(tmp_path))
    detail = _detail()

    expected = {
        "wide": (1200, 630, "share-card.png"),
        "landscape": (1600, 900, "share-card-1600x900.png"),
        "square": (1080, 1080, "share-card-square.png"),
        "story": (1080, 1920, "share-card-story.png"),
    }

    for card_format, (width, height, filename) in expected.items():
        result = export_share_card_png(detail, card_format=card_format)
        path = tmp_path / "runs" / detail.run.replay_id / filename

        assert result.ok is True
        assert result.export_path.endswith(filename)
        with Image.open(path) as image:
            assert image.size == (width, height)


def test_replay_settings_are_local_only_and_persist_safe_options(tmp_path, monkeypatch) -> None:
    monkeypatch.setenv("NASTECH_HUD_REPLAY_DIR", str(tmp_path))

    updated = update_replay_settings({
        "safe_share_mode": False,
        "include_raw_logs": True,
        "include_screenshots": True,
        "local_only": False,
    })
    loaded = get_replay_settings()

    assert updated["local_only"] is True
    assert loaded["local_only"] is True
    assert loaded["export_dir"] == str(tmp_path)
    assert loaded["safe_share_mode"] is True
    assert loaded["include_raw_logs"] is True


def test_publish_replay_copies_static_artifacts_to_local_visibility_dir(tmp_path, monkeypatch) -> None:
    monkeypatch.setenv("NASTECH_HUD_REPLAY_DIR", str(tmp_path))
    detail = _detail()

    result = publish_replay(detail, visibility="public")
    publish_dir = tmp_path / "public" / detail.run.replay_id
    manifest = json.loads((publish_dir / "publish.json").read_text(encoding="utf-8"))

    assert result.ok is True
    assert (publish_dir / "replay.html").exists()
    assert (publish_dir / "replay.redacted.json").exists()
    assert (publish_dir / "receipt.json").exists()
    assert manifest["visibility"] == "public"
    assert manifest["entry"].endswith("replay.html")
    assert manifest["view_count"] == 0
    assert manifest["fork_count"] == 0
    gallery_html = (tmp_path / "gallery.html").read_text(encoding="utf-8")
    assert "NasTech Replay Gallery" in gallery_html
    assert "No cloud upload was performed" in gallery_html
    assert "Export run" in gallery_html
    gallery = get_replay_gallery()
    assert gallery["entries"][0]["visibility"] == "public"
    assert gallery["entries"][0]["view_count"] == 0
    assert gallery["entries"][0]["fork_count"] == 0
    record_gallery_view(detail, visibility="public")
    export_fork_json(detail)
    updated_gallery = get_replay_gallery()
    assert updated_gallery["entries"][0]["view_count"] == 1
    assert updated_gallery["entries"][0]["fork_count"] == 1
    updated_gallery_html = (tmp_path / "gallery.html").read_text(encoding="utf-8")
    assert "views 1 · forks 1" in updated_gallery_html

    unpublished = unpublish_replay(detail, visibility="public")
    assert unpublished.ok is True
    assert not publish_dir.exists()
    assert get_replay_gallery()["entries"] == []
    assert "No published replays" in (tmp_path / "gallery.html").read_text(encoding="utf-8")


def test_export_clip_html_generates_standalone_animated_clip(tmp_path, monkeypatch) -> None:
    monkeypatch.setenv("NASTECH_HUD_REPLAY_DIR", str(tmp_path))
    detail = _detail()

    result = export_clip_html(detail)
    clip = (tmp_path / "runs" / detail.run.replay_id / "clip.html").read_text(encoding="utf-8")

    assert result.ok is True
    assert "NasTech Replay Clip" in clip
    assert "@keyframes rise" in clip
    assert "person@example.com" not in clip


def test_export_updates_skill_provenance_index_without_inventing_hashes(tmp_path, monkeypatch) -> None:
    monkeypatch.setenv("NASTECH_HUD_REPLAY_DIR", str(tmp_path))
    detail = _skill_detail()

    export_json(detail)
    export_json(detail)
    index = get_skill_provenance_index()
    skill = index["skills"][0]

    assert skill["name"] == "auth-helper"
    assert skill["version"] is None
    assert skill["hash"] is None
    assert skill["runs_used_in"] == [detail.run.replay_id]
    assert skill["usage_count"] == 1
    assert skill["success_count"] == 1
    assert skill["success_rate"] == 1.0
    assert skill["first_used_at"] == detail.run.started_at
    assert skill["last_used_at"] == detail.run.started_at
    assert skill["mutation_receipts"] == []


def test_export_records_skill_mutation_receipts(tmp_path, monkeypatch) -> None:
    monkeypatch.setenv("NASTECH_HUD_REPLAY_DIR", str(tmp_path))
    detail = _skill_mutation_detail()

    result = export_json(detail)
    export_json(detail)
    skill = get_skill_provenance_index()["skills"][0]
    receipts = skill["mutation_receipts"]

    assert skill["name"] == "auth-helper"
    assert len(receipts) == 1
    assert receipts[0]["event_type"] == "skill_created"
    assert receipts[0]["replay_id"] == detail.run.replay_id
    assert receipts[0]["receipt_hash"] == result.receipt_hash
    assert receipts[0]["redacted_replay_hash"] == result.redacted_replay_hash
